CREATE TABLE `points_bot_scratch_round` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `chat_id` bigint NOT NULL COMMENT '群聊ID',
    `message_id` bigint DEFAULT NULL COMMENT '游戏面板消息ID',
    `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态 OPEN/CLOSED/CANCELLED',
    `entry_cost` int NOT NULL DEFAULT 50 COMMENT '每格参与积分',
    `draw_at` datetime NOT NULL COMMENT '计划开奖时间',
    `drawn_at` datetime DEFAULT NULL COMMENT '实际开奖时间',
    `jackpot_cell` int DEFAULT NULL COMMENT '大奖格子序号',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_scratch_chat_status` (`chat_id`, `status`),
    KEY `idx_scratch_draw_at` (`draw_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人泡沫刮刮乐轮次';

CREATE TABLE `points_bot_scratch_entry` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `round_id` bigint NOT NULL COMMENT '刮刮乐轮次ID',
    `chat_id` bigint NOT NULL COMMENT '群聊ID',
    `cell_number` int NOT NULL COMMENT '选择的格子序号 1-9',
    `user_id` bigint NOT NULL COMMENT 'Telegram用户ID',
    `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Telegram用户名',
    `display_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '展示名称',
    `reward_points` int DEFAULT NULL COMMENT '开奖所得积分',
    `is_jackpot` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否命中大奖',
    `settled_at` datetime DEFAULT NULL COMMENT '积分结算时间',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_scratch_round_cell` (`round_id`, `cell_number`),
    UNIQUE KEY `uniq_scratch_round_user` (`round_id`, `user_id`),
    KEY `idx_scratch_chat_user` (`chat_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人泡沫刮刮乐参与记录';
