CREATE TABLE `points_bot_brain_round` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `chat_id` bigint NOT NULL COMMENT '群聊ID',
    `message_id` bigint DEFAULT NULL COMMENT '游戏面板消息ID',
    `status` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'REGISTERING/ACTIVE/SETTLED/CANCELLED/INVALID',
    `is_peak` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否巅峰局',
    `config_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '本轮配置快照',
    `question_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '题型',
    `question_prompt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公开题面',
    `hidden_prompt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '闪记隐藏后的题面',
    `answer_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '结构化答案',
    `explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '结算说明',
    `entry_cost` int NOT NULL COMMENT '报名积分',
    `min_players` int NOT NULL COMMENT '最少参与人数',
    `max_players` int NOT NULL COMMENT '最多参与人数',
    `registration_ends_at` datetime NOT NULL COMMENT '报名截止时间',
    `started_at` datetime DEFAULT NULL COMMENT '答题开始时间',
    `question_hides_at` datetime DEFAULT NULL COMMENT '闪记题隐藏时间',
    `answer_ends_at` datetime DEFAULT NULL COMMENT '答题截止时间',
    `settled_at` datetime DEFAULT NULL COMMENT '结算时间',
    `total_pot` int NOT NULL DEFAULT 0 COMMENT '本轮报名奖池',
    `champion_user_id` bigint DEFAULT NULL COMMENT '第一名用户ID',
    `jackpot_before` int DEFAULT NULL COMMENT '结算前累积奖池',
    `jackpot_after` int DEFAULT NULL COMMENT '结算后累积奖池',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_brain_round_chat_status` (`chat_id`, `status`),
    KEY `idx_brain_round_registration` (`status`, `registration_ends_at`),
    KEY `idx_brain_round_answer` (`status`, `answer_ends_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人Brain轮次';

CREATE TABLE `points_bot_brain_entry` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `round_id` bigint NOT NULL COMMENT 'Brain轮次ID',
    `chat_id` bigint NOT NULL COMMENT '群聊ID',
    `user_id` bigint NOT NULL COMMENT 'Telegram用户ID',
    `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Telegram用户名',
    `display_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '展示名称',
    `entry_cost` int NOT NULL COMMENT '实际报名积分',
    `submission_count` int NOT NULL DEFAULT 0 COMMENT '提交次数',
    `is_correct` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否答对',
    `correct_at` datetime DEFAULT NULL COMMENT '首次答对时间',
    `effective_correct_at` datetime DEFAULT NULL COMMENT '含二次提交惩罚的排名时间',
    `rank_no` int DEFAULT NULL COMMENT '答对排名',
    `reward_points` int DEFAULT NULL COMMENT '所得奖励',
    `counted_play` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否计入每日次数',
    `settled_at` datetime DEFAULT NULL COMMENT '结算时间',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_brain_round_user` (`round_id`, `user_id`),
    KEY `idx_brain_entry_chat_user` (`chat_id`, `user_id`),
    KEY `idx_brain_entry_correct` (`round_id`, `is_correct`, `effective_correct_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人Brain参与记录';

CREATE TABLE `points_bot_brain_jackpot` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `chat_id` bigint NOT NULL COMMENT '群聊ID',
    `jackpot_points` int NOT NULL DEFAULT 0 COMMENT '累积奖池积分',
    `completed_rounds` int NOT NULL DEFAULT 0 COMMENT '已完成有效局数',
    `peak_pending` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否等待巅峰局',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人id',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人id',
    `del_flag` int DEFAULT '0' COMMENT '是否删除 0 未删除 1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_brain_jackpot_chat` (`chat_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人Brain累积奖池';
