CREATE TABLE `points_bot_red_packet` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `chat_id` bigint NOT NULL COMMENT '积分群聊ID',
    `message_id` bigint DEFAULT NULL COMMENT 'Telegram红包面板消息ID',
    `creator_user_id` bigint NOT NULL COMMENT '发起人Telegram用户ID',
    `creator_username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发起人Telegram用户名',
    `creator_display_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发起人展示名称',
    `greeting` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '红包祝福语',
    `total_points` int NOT NULL COMMENT '红包总积分',
    `total_count` int NOT NULL COMMENT '红包总个数',
    `remaining_points` int NOT NULL COMMENT '待领取积分',
    `remaining_count` int NOT NULL COMMENT '待领取红包个数',
    `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PUBLISHING/OPEN/FINISHED/EXPIRED/CANCELLED',
    `published_at` datetime DEFAULT NULL COMMENT '面板发布时间',
    `panel_synced_at` datetime DEFAULT NULL COMMENT '面板最近同步时间',
    `expires_at` datetime NOT NULL COMMENT '过期时间',
    `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
    `refunded_points` int NOT NULL DEFAULT '0' COMMENT '已退回积分',
    `refunded_at` datetime DEFAULT NULL COMMENT '退款时间',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人ID',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人ID',
    `del_flag` int NOT NULL DEFAULT '0' COMMENT '是否删除 0未删除 1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_red_packet_message` (`chat_id`, `message_id`),
    KEY `idx_red_packet_status_expires` (`status`, `expires_at`, `id`),
    KEY `idx_red_packet_creator` (`chat_id`, `creator_user_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人群红包';

CREATE TABLE `points_bot_red_packet_claim` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `red_packet_id` bigint NOT NULL COMMENT '红包ID',
    `chat_id` bigint NOT NULL COMMENT '积分群聊ID',
    `user_id` bigint NOT NULL COMMENT '领取人Telegram用户ID',
    `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '领取人Telegram用户名',
    `display_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '领取人展示名称',
    `points` int NOT NULL COMMENT '领取积分',
    `claimed_at` datetime NOT NULL COMMENT '领取时间',
    `create_datetime` datetime DEFAULT NULL COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL COMMENT '修改时间',
    `create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人ID',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人ID',
    `del_flag` int NOT NULL DEFAULT '0' COMMENT '是否删除 0未删除 1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_red_packet_claim_user` (`red_packet_id`, `user_id`),
    KEY `idx_red_packet_claim_packet` (`red_packet_id`, `id`),
    KEY `idx_red_packet_claim_user` (`chat_id`, `user_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人群红包领取记录';
