CREATE TABLE `points_bot_redeem_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `request_id` varchar(64) NOT NULL COMMENT '客户端幂等请求ID',
    `active_guard` tinyint DEFAULT NULL COMMENT '进行中唯一占位，结束后必须释放为NULL',
    `web_user_id` bigint NOT NULL COMMENT '发起兑换的Web用户ID',
    `chat_id` bigint NOT NULL COMMENT '积分群/频道ID快照',
    `telegram_user_id` bigint NOT NULL COMMENT 'Telegram用户ID快照',
    `config_id` bigint NOT NULL COMMENT '兑换配置ID快照',
    `config_name` varchar(100) NOT NULL COMMENT '兑换配置名称快照',
    `redeem_type` varchar(32) NOT NULL COMMENT 'CREATE_ACCOUNT注册账号 RENEW续费',
    `redeem_days` int NOT NULL COMMENT '兑换天数快照',
    `required_points` int NOT NULL COMMENT '消费积分快照',
    `server_id` bigint NOT NULL COMMENT 'Emby服务器ID快照',
    `server_name` varchar(100) DEFAULT NULL COMMENT 'Emby服务器名称快照',
    `target_user_id` bigint DEFAULT NULL COMMENT '续费目标Web用户ID或新建用户ID',
    `target_user_name` varchar(100) DEFAULT NULL COMMENT '目标Emby用户名',
    `status` varchar(20) NOT NULL COMMENT 'PROCESSING SUCCESS REFUNDED',
    `result_message` varchar(255) DEFAULT NULL COMMENT '可向用户展示的处理结果',
    `expiration_date` datetime DEFAULT NULL COMMENT '兑换完成后的到期时间',
    `finished_at` datetime DEFAULT NULL COMMENT '处理完成时间',
    `create_datetime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_datetime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人名称',
    `update_user_name` varchar(64) DEFAULT NULL COMMENT '修改人名称',
    `update_user_id` bigint DEFAULT NULL COMMENT '修改人ID',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人ID',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除 0未删除 1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_points_redeem_web_request` (`web_user_id`, `request_id`),
    UNIQUE KEY `uniq_points_redeem_active_user` (`chat_id`, `telegram_user_id`, `active_guard`),
    KEY `idx_points_redeem_web_created` (`web_user_id`, `create_datetime`),
    KEY `idx_points_redeem_tg_created` (`telegram_user_id`, `create_datetime`),
    KEY `idx_points_redeem_status_created` (`status`, `create_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分机器人Web兑换记录';
